// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjfcIBhwtwc_SB3BdjT0S8a4uheNT9Csw',
    appId: '1:689841448062:web:fc67da9395c6865498642f',
    messagingSenderId: '689841448062',
    projectId: 'ecommerece-c1601',
    authDomain: 'ecommerece-c1601.firebaseapp.com',
    storageBucket: 'ecommerece-c1601.appspot.com',
    measurementId: 'G-C88H8M15LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQfJb-QkHNa7KuNPuq3v54gFglYoTW7w',
    appId: '1:689841448062:android:9a27cf45c22c14e598642f',
    messagingSenderId: '689841448062',
    projectId: 'ecommerece-c1601',
    storageBucket: 'ecommerece-c1601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDFw-OLZFLhZ2gJ4m_6emHN3ht9mEUQ-U',
    appId: '1:689841448062:ios:44266a0a8b522f6c98642f',
    messagingSenderId: '689841448062',
    projectId: 'ecommerece-c1601',
    storageBucket: 'ecommerece-c1601.appspot.com',
    iosBundleId: 'com.example.ecommerece',
  );
}
